# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='local_filename',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
